# Getting Started with Python

## Installation

### To install Anaconda for Python 3.5

Download and install Anaconda Python 3.5 from https://www.continuum.io/downloads

Open a terminal
```bash
conda update conda
conda update anaconda
```

### (OPTIONAL) Using Jupyter remotely

For people with a valid Duke NetID, you can get access to running Jupyter and RStudio instances [here](https://vm-manage.oit.duke.edu/containers)

### (OPTIONAL) To install R

- If you want `conda` to manage your R packages

```bash
conda install -y -c r r-irkernel r-recommended r-essentials
```

- If you have an existing R installation that you want to use

Start R
```R
install.packages(c('rzmq','repr','IRkernel','IRdisplay'),
                 repos = c('http://irkernel.github.io/', getOption('repos')))
IRkernel::installspec()
```


### (OPTIONAL) Integrated Development Environments (IDE)

- [RStudio for R](https://www.rstudio.com)
- [Rodeo for Python](https://www.yhat.com/products/rodeo)


### Check

Open terminal
```
jupyter notebook
```

See if the installed kernels are found in the drop-down menu.

## Live Demo of Jupyter Features

* Administration interface
    * Files
    * Running
    * Uploading notebooks
    * New notebook
* Notebook interface
    * Menu
    * Cells
    * Keyboard shortcuts
    * Getting help
* Notebook magics
    * `bash`
    * `R`
    * Other

## Using Markdown in Jupyter for Literate Programming

[Markdown Syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax)

## Elements of Python

### Types

In [1]:
True, False, 1, 2, 3, 3.14, 2.78, "hello", 'world'

(True, False, 1, 2, 3, 3.14, 2.78, 'hello', 'world')

### Operators

In [3]:
-1, 2+3, 7%3, 7/2, 7//2, 2**4, True & True, True & False, True | False, 3 <= 4

(-1, 5, 1, 3.5, 3, 16, True, False, True, True)

### Variables and Assignment

In [8]:
a = 3
b = 4
c = a + b

In [9]:
a, b, c

(3, 4, 7)

### Containers (Collections)

In [18]:
a_tuple = (1, 2, 3, 4)
a_list = ['a', 'b', 'c', 'd']
a_set = {1, 2, 2, 3, 3, 3}
a_dict = {'c': 1, 'b': 2, 'a': 3}

In [19]:
a_tuple

(1, 2, 3, 4)

In [20]:
a_list

['a', 'b', 'c', 'd']

In [21]:
a_set

{1, 2, 3}

In [22]:
a_dict

{'a': 3, 'b': 2, 'c': 1}

In [23]:
from collections import OrderedDict

In [31]:
a_ordereddict = OrderedDict([('c', 1), ('b', 2), ('a', 3)])
a_ordereddict

OrderedDict([('c', 1), ('b', 2), ('a', 3)])

## Indexing a container

In [28]:
a_tuple[0]

1

In [29]:
a_list[1:4]

['b', 'c', 'd']

In [32]:
a_dict['b']

2

In [33]:
a_ordereddict['c']

1

## Controlling program flow

In [35]:
'a' if 3 < 4 else 'b'

'a'

In [36]:
'a' if 4 < 3 else 'b'

'b'

In [42]:
score = np.random.uniform(60, 100)

if score > 90:
    print('A')
elif score > 80:
    print('B')
else:
    print('C')

B


### Looping

In [44]:
list(range(10, 20, 2))

[10, 12, 14, 16, 18]

In [45]:
for i in range(10, 20, 2):
    print(i, i**2)

10 100
12 144
14 196
16 256
18 324


In [47]:
max_count = 5
count = 0
while (count < max_count):
    print(count)
    count += 1

0
1
2
3
4


### List Comprehension

In [48]:
[x**2 for x in range(5)]

[0, 1, 4, 9, 16]

In [50]:
[x**2 for x in range(5) if x % 2 == 0]

[0, 4, 16]

### User-defined functions

In [51]:
def f(x):
    return x

In [52]:
f(3.14)

3.14

In [53]:
def g(a, b):
    return a + b

In [54]:
g(3, 4)

7

#### Default arguments

In [60]:
def h(a= 0 , b = 1, c = 2):
    return a + 2*b + 3*c

In [61]:
h()

8

In [62]:
h(1)

9

In [63]:
h(1, 2)

11

In [64]:
h(1, 2, 3)

14

In [66]:
h(c = 1, b = 2, a = 3)

10

### Using Libraries

In [67]:
import math

math.pi

3.141592653589793

In [70]:
import numpy as np

np.linspace(0, 1, 11)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

In [3]:
from numpy.random import rand

In [72]:
rand(4)

array([ 0.68377289,  0.49935727,  0.38924345,  0.65851496])

## Working with vectors and arrays

In [8]:
A = np.random.random((3,4))
A

array([[ 0.7969584 ,  0.00836062,  0.09457887,  0.05256916],
       [ 0.60802338,  0.16084964,  0.64331605,  0.09452616],
       [ 0.31569141,  0.14839923,  0.60148372,  0.36204727]])

### Indexing a matrix

In [9]:
A[0,0]

0.79695840138509744

In [10]:
A[2,3]

0.36204726842686386

In [11]:
A[1]

array([ 0.60802338,  0.16084964,  0.64331605,  0.09452616])

In [12]:
A[1, :]

array([ 0.60802338,  0.16084964,  0.64331605,  0.09452616])

In [13]:
A[:, 2]

array([ 0.09457887,  0.64331605,  0.60148372])

In [15]:
A[:2, 1:]

array([[ 0.00836062,  0.09457887,  0.05256916],
       [ 0.16084964,  0.64331605,  0.09452616]])

In [16]:
A[1:3, 1:3]

array([[ 0.16084964,  0.64331605],
       [ 0.14839923,  0.60148372]])

### Vectorized functions

In [17]:
A * 10

array([[ 7.96958401,  0.08360619,  0.94578866,  0.52569156],
       [ 6.08023377,  1.60849639,  6.43316053,  0.94526158],
       [ 3.15691409,  1.48399234,  6.01483725,  3.62047268]])

In [19]:
A.sum()

3.8868039055060328

In [20]:
A.sum(axis = 0)

array([ 1.72067319,  0.31760949,  1.33937864,  0.50914258])

In [21]:
A.sum(axis = 1)

array([ 0.95246704,  1.50671523,  1.42762164])

In [23]:
A.max(axis = 0)

array([ 0.7969584 ,  0.16084964,  0.64331605,  0.36204727])

In [25]:
A.T @ A

array([[ 1.10449619,  0.15131177,  0.65640987,  0.21366476],
       [ 0.15131177,  0.04796484,  0.19352762,  0.06937155],
       [ 0.65640987,  0.19352762,  0.78458338,  0.28354767],
       [ 0.21366476,  0.06937155,  0.28354767,  0.14277694]])

## Exercises

## Version information

In [73]:
%load_ext version_information
%version_information

Software versions
Python 3.5.2 64bit [GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]
IPython 5.0.0
OS Darwin 15.6.0 x86_64 i386 64bit
Mon Aug 15 14:11:39 2016 EDT